config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :recipes  do
  get 'category/:category_name', on: :collection, action: 'recipes_by_category', as: 'category' 
  resources :reviews
  end
  
 
  
  root 'recipes#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
     has_and_belongs_to_many :recipes
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
    belongs_to :user
    has_and_belongs_to_many :categories
    has_many :reviews
   
    has_attached_file :recipe_img, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :recipe_img, content_type: /\Aimage\/.*\Z/
end

app/models/review.rb
class Review < ActiveRecord::Base
    belongs_to :user
    belongs_to :recipe
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :recipes # association
  has_many :reviews
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :find_recipe, only: [:show, :edit,:destroy, :update,:add_category] 
    before_action :authenticate_user!, only: [:new, :edit]
    def index
        @recipes=Recipe.all
    end
    
    def new
        @recipe= current_user.recipes.new
    end
    
    def create
        @recipe = current_user.recipes.new(recipe_params)
        add_category
        
        if @recipe.save
            redirect_to recipes_path
        else
            render 'new'
        end
    end
    
    def show
        @reviews = @recipe.reviews.to_a
        if @reviews.blank?
            @avg_rating = 0 
        else
            @avg_rating= @recipe.reviews.average(:rating).round(2)
        end
    end
    def destroy
        @recipe.destroy
        redirect_to recipes_path
    end
    def edit
        @categories=Category.all.map{|c| [c.name, c.id]}
    end
    
    def update 
        add_category
        if @recipe.update_attributes(recipe_params)
            redirect_to @recipe
        else
            render 'edit'
        end
    end
    
    def find_recipe
        @recipe = Recipe.find(params[:id])
        
    end
    # strong parameters
    def recipe_params
        
        params.require(:recipe).permit(:title, :description, :publisher, :recipe_img)
    end
    def add_category
        
        @recipe.categories=[]
        @category_ids= params[:recipe][:category_ids].delete_if{|i|i==""}
        @category_ids.each do |c|
            @category = Category.find(c) 
            @recipe.categories << @category if (@recipe.categories.include?(@category)==false)
        end
        
    end
    def recipes_by_category
        Category.all.each {|c| @category= c if params[:category_name]==c.name}
    end
    
end


#Parameters: {"utf8"=>"✓", "authenticity_token"=>"PA6WpN9vY+CbdpjyPntZeTWZ3BIPJwm1It8trF/MlXCaB0cHkOWebVZFE0kSq8EJS0Z/tQWKpyYUKwniMYN7Dg==", "recipe"=>{"title"=>"chicken", "description"=>"pollo frito", "publisher"=>"cubano"}, "commit"=>"Submit"}
#params is a built in hash that takes whatsever in your route and put in a hash
#params is a hash with recipe key and another hash in the value with the title description and publisher

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :find_recipe
    before_action :find_review, only: [:edit, :update, :destroy ]
    before_action :authenticate_user!, only: [:new, :edit]
    def new
        @review=Review.new
        
    end
    
    def create
        @review = current_user.reviews.new(review_params) 
        @review.recipe_id= @recipe.id
        if (@review.save) 
           redirect_to recipe_path(@recipe)
        else
            render 'new'
        end 
    end
    
    def edit
        
    end
    
    def update
        if @review.update_attributes(review_params)
            redirect_to recipe_path(@recipe)
        else
            render 'edit'
        end
    end
    
    def destroy
        @review.destroy
        redirect_to recipe_path(@recipe)
    end
    
    def find_recipe
        @recipe = Recipe.find(params[:recipe_id])
        
    end
    
    def find_review
        @review = Review.find(params[:id])
        
    end

    def review_params
        params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecipesReview</title>
  <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
  
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav  class="navbar navbar-default navbar-fixed-top navbar-inverse navbar-custom ">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
        </button>
        
        <ul class="nav navbar-nav navbar-left" >
          <li  id= "logo"><%= link_to((image_tag "logo.png"), recipes_path, class: "navbar-brand page-scroll") %></li>
          <li><%= link_to("Recipe Reviews", recipes_path, class: " title navbar-brand page-scroll")%></li>
        </ul>
          
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav  navbar-right "> 
          <li><%= link_to("Add recipe", new_recipe_path, class: "page-scroll") %></li>
          <% if current_user.nil? %>
            <li><%= link_to("Log in", new_user_session_path, class: "page-scroll") %></li> 
            <li><%= link_to("Sign up", new_user_registration_path, class: "page-scroll") %></li>
          <% else %>
            <li><%=link_to("Settings", edit_user_registration_path, class: "page-scroll" )%></li>
            <li><%= link_to("Log out", destroy_user_session_path, method: :delete, class: "page-scroll") %></li>
          <% end %>
          <li role="presentation" class="dropdown">
            <a class=" dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              Categories
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <% Category.all.each do |c| %>
                <li id="category"> <%= link_to "#{c.name}", category_recipes_path(c.name) %> </li>
              <%end%>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
    
  <div class="container">
    <p class="notice"><%= notice %></p>
    
    <p class="alert " role="alert"><%= alert %></p>
    
    <%= yield %>
  </div>

  
  <nav class=" footer navbar  navbar-fixed-bottom" role="navigation">
    <div class="container text-center">
      Copyright &copy; 2016 Yamilet Diaz
    </div>
  </nav>          

</body>

</html>

app/views/recipes/_form.html.erb
<%= simple_form_for @recipe, html: { multipart: true } do |f| %>
    <div class="panel-body">
        <div class="form-group">
            <%= f.input :title, placeholder: 'Enter title' %>
            <%= f.input :publisher, placeholder: 'Publisher' %>
            <%= f.input :description, placeholder: 'Description' %>
            <%= f.association :categories, as: :check_boxes %>
            <%=f.label :image %>
            <%= f.file_field :recipe_img %>
        </div>
    </div>
    <div class="panel-footer">
        <%= f.button :submit, class: "btn btn-primary" %>
    </div>
<% end %>

app/views/recipes/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="panel panel-default">
    <div class="panel-heading"> 
      <h2>Edit Recipe</h2>
    </div>
    <%= render 'form'%>
  </div>
</div>

app/views/recipes/index.html.erb
<% if user_signed_in?%>
    <%@recipes=current_user.recipes%>
<%end%>

<div class= "row responsive">
    <%@recipes.each do |r| %>
        <div class=" col-lg-3 col-md-4 col-sm-6 col-xs-12">
            <div class="panel panel-default gallery-item ">
                <%= link_to  recipe_path(r.id) do %>
                    <%= image_tag r.recipe_img.url, class:"image img-responsive img-rounded img-thumbnail", alt: 'a recipe'%>
                <% end %>
            </div>
        </div>
    <% end%>
</div>

app/views/recipes/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="panel panel-default">
    <div class="panel-heading"> 
      <h2>New Recipe</h2>
    </div>
    <%= render 'form'%>
  </div>  
</div>

app/views/recipes/recipes_by_category.html.erb
<div class= "row responsive">
    <% if user_signed_in?%>
        <% @category.recipes.each do |r| %>
            <%if r.user_id==current_user.id%>
               <div class=" col-lg-3 col-md-4 col-sm-6 col-xs-12">
                    <div class="panel panel-default gallery-item ">
                        <%= link_to  recipe_path(r) do %>
                            <%= image_tag r.recipe_img.url, class:"image img-responsive img-rounded img-thumbnail", alt: 'a recipe'%>
                        <% end %>
                    </div>
                </div>
            <%end%>    
        <%end%>
    <%else%>
        <% @category.recipes.each do |r| %>
            <div class=" col-lg-3 col-md-4 col-sm-6 col-xs-12">
                <div class="panel panel-default gallery-item ">
                    <%= link_to  recipe_path(r) do %>
                        <%= image_tag r.recipe_img.url, class:"image img-responsive img-rounded img-thumbnail", alt: 'a recipe'%>
                    <% end %>
                </div>
            </div>
        <% end%>
    <%end%>
</div>


 

app/views/recipes/show.html.erb
<div class="row container">
    <div class="col-md-4 col-sm-6">
        <div id="show-img" class="panel panel-default">
            <%=image_tag @recipe.recipe_img.url,  class:" img-rounded img-thumbnail", alt: 'a recipe'%>
        </div>
        <div class="panel panel-default reviews-section">
            <div class="panel-body">
                <h2>Reviews</h2>
                <% @recipe.reviews.each do |review| %>
                    <div class="reviews">
                        <div class="star-rating" data-score= <%= review.rating %> ></div>
                        <p><%= review.comment %></p>
                    </div>
                    <% if (user_signed_in?)&& (review.user!=nil) && (review.user.id==current_user.id)%>
                        <div>
                            <%=link_to("Edit Review", edit_recipe_review_path(@recipe, review), class:"btn btn-info" )%>
                            <%=link_to("Delete Review", recipe_review_path(@recipe, review), method: :delete, class:"btn btn-danger" )%>
                        </div>
                    <%end%>
                <%end%>
                <hr>
                <% if (user_signed_in?)%>
                    <%=link_to("Add Review", new_recipe_review_path(@recipe),  class:"btn btn-lg btn-default" )%>
                <%end%>
            </div>
        </div>  
    </div>
       
    <div class="col-md-8 col-sm-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3><%= @recipe.title %></h3>
            </div>
            <div class="panel-body">
                <p>Published by <span class="h3"><%= @recipe.publisher %></span></p>
                <h4>Categories: <span class="h5"><%= @recipe.categories.map(&:name).join(', ') %></span></h4>
                <br>
                <h4>Average Rating</h4>
                <div class='star-rating' data-score=<%= @avg_rating %>></div>
                <em>Based in <%= "#{@reviews.size} reviews" %></em>
                <br>
                <br>
                <h5>Ingredients:</h5>
                <ul>
                    <p><%= simple_format(@recipe.description)%></p>
                <ul>
            </div>
            <div class=" panel-footer buttons">
                <% if user_signed_in?%>
                    <%=link_to("Edit Recipe",edit_recipe_path(@recipe), class:"btn btn-info")%>
                    <%=link_to("Delete Recipe", recipe_path(@recipe), method: :delete, class:"btn btn-danger")%>
                <%end%>
            </div>
        </div>
    </div>
</div>    
    <script>
    $('.star-rating').raty({
      path: '/images/ratyrate',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
   </script>    
  
    
   

app/views/reviews/_form.html.erb
<%= simple_form_for ([@recipe, @review])do |f| %>
    <div class="panel-body">
        <div class="form-group">
            <%= f.label :rating%>
            <div id='star-rating'></div><br>
            <%= f.input :comment, placeholder: 'Comment' %>
        </div>
    </div>
    <div class="panel-footer">
        <%= f.button :submit, class: "btn btn-primary" %>
    </div>
<% end %>

<script>
$('#star-rating').raty({
    path: '/images/ratyrate',
    scoreName: 'review[rating]'
});
</script>

app/views/reviews/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="panel panel-default">
    <div class="panel-heading"> 
      <h2>Edit Review</h2>
    </div>
    <%= render 'form'%>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="panel panel-default">
    <div class="panel-heading"> 
      <h2>New Review</h2>
    </div>
    <%= render 'form'%>
  </div>
</div>